# create_S4_plan_files.ps1
# Auto-generated by generate_create_script.ps1
# Creates all files and folders for S4_plan
# Usage: .\create_S4_plan_files.ps1

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Base      = "$ScriptDir\S4_plan"

Write-Host "[S4_plan] Creating folders..."
@(
    "$Base\S4_Client",
    "$Base\S4_Client\Forms",
    "$Base\S4_Client\Models",
    "$Base\S4_Client\Services"
) | ForEach-Object { New-Item -ItemType Directory -Force -Path $_ | Out-Null }

Write-Host "[S4_plan] Writing files..."

# S4_Client\AppState.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\AppState.cs",
@'
namespace S4_Client;
public static class AppState
{
    public static string? Token { get; set; }
    public static string? Username { get; set; }
    public static string? Role { get; set; }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Forms\LoginForm.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Forms\LoginForm.cs",
@'
using S4_Client.Services;

namespace S4_Client.Forms;

public class LoginForm : Form
{
    private readonly ApiService _api = new ApiService();

    private Label lblTitle;
    private Label lblUsername;
    private TextBox txtUsername;
    private Label lblPassword;
    private TextBox txtPassword;
    private Button btnLogin;
    private Button btnRegister;
    private Label lblError;

    public LoginForm()
    {
        this.Text = "Вход";
        this.Size = new Size(400, 280);
        this.StartPosition = FormStartPosition.CenterScreen;
        this.FormBorderStyle = FormBorderStyle.FixedDialog;
        this.MaximizeBox = false;

        lblTitle = new Label();
        lblTitle.Text = "Магазин";
        lblTitle.Font = new Font("Segoe UI", 16f, FontStyle.Bold);
        lblTitle.TextAlign = ContentAlignment.MiddleCenter;
        lblTitle.Location = new Point(0, 15);
        lblTitle.Size = new Size(384, 40);

        lblUsername = new Label();
        lblUsername.Text = "Имя пользователя:";
        lblUsername.Location = new Point(40, 70);
        lblUsername.Size = new Size(150, 20);

        txtUsername = new TextBox();
        txtUsername.Location = new Point(40, 92);
        txtUsername.Size = new Size(300, 25);

        lblPassword = new Label();
        lblPassword.Text = "Пароль:";
        lblPassword.Location = new Point(40, 125);
        lblPassword.Size = new Size(150, 20);

        txtPassword = new TextBox();
        txtPassword.Location = new Point(40, 147);
        txtPassword.Size = new Size(300, 25);
        txtPassword.PasswordChar = '*';

        btnLogin = new Button();
        btnLogin.Text = "Войти";
        btnLogin.Location = new Point(40, 185);
        btnLogin.Size = new Size(140, 32);
        btnLogin.Click += BtnLogin_Click;

        btnRegister = new Button();
        btnRegister.Text = "Регистрация";
        btnRegister.Location = new Point(200, 185);
        btnRegister.Size = new Size(140, 32);
        btnRegister.Click += BtnRegister_Click;

        lblError = new Label();
        lblError.Text = "";
        lblError.ForeColor = Color.Red;
        lblError.Location = new Point(40, 225);
        lblError.Size = new Size(300, 20);

        this.Controls.Add(lblTitle);
        this.Controls.Add(lblUsername);
        this.Controls.Add(txtUsername);
        this.Controls.Add(lblPassword);
        this.Controls.Add(txtPassword);
        this.Controls.Add(btnLogin);
        this.Controls.Add(btnRegister);
        this.Controls.Add(lblError);
    }

    private void BtnLogin_Click(object? sender, EventArgs e)
    {
        lblError.Text = "";
        if (string.IsNullOrWhiteSpace(txtUsername.Text) || string.IsNullOrWhiteSpace(txtPassword.Text))
        {
            lblError.Text = "Заполните все поля";
            return;
        }

        var result = _api.Login(txtUsername.Text.Trim(), txtPassword.Text);
        if (result != null && !string.IsNullOrEmpty(result.Token))
        {
            AppState.Token = result.Token;
            AppState.Username = result.Username;
            AppState.Role = result.Role;
            var mainForm = new MainForm();
            mainForm.Show();
            this.Close();
        }
        else
        {
            lblError.Text = "Неверное имя пользователя или пароль";
        }
    }

    private void BtnRegister_Click(object? sender, EventArgs e)
    {
        var registerForm = new RegisterForm();
        registerForm.ShowDialog(this);
    }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Forms\MainForm.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Forms\MainForm.cs",
@'
namespace S4_Client.Forms;

public class MainForm : Form
{
    private Panel pnlSidebar;
    private Panel pnlContent;
    private Label lblUser;
    private Button btnProducts;
    private Button btnOrders;
    private Button btnLogout;

    public MainForm()
    {
        this.Text = "Магазин";
        this.Size = new Size(900, 600);
        this.StartPosition = FormStartPosition.CenterScreen;
        this.MinimumSize = new Size(700, 450);

        // Sidebar
        pnlSidebar = new Panel();
        pnlSidebar.Width = 140;
        pnlSidebar.Dock = DockStyle.Left;
        pnlSidebar.BackColor = Color.FromArgb(45, 45, 48);

        lblUser = new Label();
        lblUser.Text = $"Привет,\n{AppState.Username}";
        lblUser.ForeColor = Color.White;
        lblUser.Location = new Point(5, 15);
        lblUser.Size = new Size(130, 45);
        lblUser.TextAlign = ContentAlignment.MiddleCenter;
        lblUser.Font = new Font("Segoe UI", 9f);

        btnProducts = new Button();
        btnProducts.Text = "Товары";
        btnProducts.Location = new Point(10, 70);
        btnProducts.Size = new Size(120, 36);
        btnProducts.FlatStyle = FlatStyle.Flat;
        btnProducts.ForeColor = Color.White;
        btnProducts.BackColor = Color.FromArgb(62, 62, 66);
        btnProducts.FlatAppearance.BorderColor = Color.FromArgb(80, 80, 85);
        btnProducts.Click += (s, e) => ShowProducts();

        btnOrders = new Button();
        btnOrders.Text = "Заказы";
        btnOrders.Location = new Point(10, 115);
        btnOrders.Size = new Size(120, 36);
        btnOrders.FlatStyle = FlatStyle.Flat;
        btnOrders.ForeColor = Color.White;
        btnOrders.BackColor = Color.FromArgb(62, 62, 66);
        btnOrders.FlatAppearance.BorderColor = Color.FromArgb(80, 80, 85);
        btnOrders.Click += (s, e) => ShowOrders();

        btnLogout = new Button();
        btnLogout.Text = "Выйти";
        btnLogout.Dock = DockStyle.Bottom;
        btnLogout.Height = 36;
        btnLogout.FlatStyle = FlatStyle.Flat;
        btnLogout.ForeColor = Color.White;
        btnLogout.BackColor = Color.FromArgb(80, 40, 40);
        btnLogout.FlatAppearance.BorderColor = Color.FromArgb(100, 50, 50);
        btnLogout.Click += BtnLogout_Click;

        pnlSidebar.Controls.Add(lblUser);
        pnlSidebar.Controls.Add(btnProducts);
        pnlSidebar.Controls.Add(btnOrders);
        pnlSidebar.Controls.Add(btnLogout);

        // Content area
        pnlContent = new Panel();
        pnlContent.Dock = DockStyle.Fill;
        pnlContent.BackColor = Color.White;

        this.Controls.Add(pnlContent);
        this.Controls.Add(pnlSidebar);

        // Show products by default
        ShowProducts();
    }

    private void ShowProducts()
    {
        pnlContent.Controls.Clear();
        var ctrl = new ProductsControl();
        ctrl.Dock = DockStyle.Fill;
        pnlContent.Controls.Add(ctrl);
    }

    private void ShowOrders()
    {
        pnlContent.Controls.Clear();
        var ctrl = new OrdersControl();
        ctrl.Dock = DockStyle.Fill;
        pnlContent.Controls.Add(ctrl);
    }

    private void BtnLogout_Click(object? sender, EventArgs e)
    {
        AppState.Token = null;
        AppState.Username = null;
        AppState.Role = null;
        var loginForm = new LoginForm();
        loginForm.Show();
        this.Close();
    }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Forms\OrderDialog.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Forms\OrderDialog.cs",
@'
using S4_Client.Models;
using S4_Client.Services;

namespace S4_Client.Forms;

public class OrderDialog : Form
{
    private readonly ApiService _api;
    private List<Product> _products = new List<Product>();

    private Label lblProduct;
    private ComboBox cmbProduct;
    private Label lblQuantity;
    private NumericUpDown nudQuantity;
    private Label lblTotal;
    private Button btnOrder;
    private Button btnCancel;
    private Label lblError;

    public OrderDialog(ApiService api)
    {
        _api = api;

        this.Text = "Создать заказ";
        this.Size = new Size(360, 240);
        this.StartPosition = FormStartPosition.CenterParent;
        this.FormBorderStyle = FormBorderStyle.FixedDialog;
        this.MaximizeBox = false;
        this.MinimizeBox = false;

        lblProduct = new Label();
        lblProduct.Text = "Товар:";
        lblProduct.Location = new Point(20, 25);
        lblProduct.Size = new Size(90, 20);

        cmbProduct = new ComboBox();
        cmbProduct.Location = new Point(120, 22);
        cmbProduct.Size = new Size(210, 25);
        cmbProduct.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbProduct.SelectedIndexChanged += CmbProduct_SelectedIndexChanged;

        lblQuantity = new Label();
        lblQuantity.Text = "Количество:";
        lblQuantity.Location = new Point(20, 65);
        lblQuantity.Size = new Size(90, 20);

        nudQuantity = new NumericUpDown();
        nudQuantity.Location = new Point(120, 62);
        nudQuantity.Size = new Size(120, 25);
        nudQuantity.Minimum = 1;
        nudQuantity.Maximum = 999;
        nudQuantity.Value = 1;
        nudQuantity.ValueChanged += NudQuantity_ValueChanged;

        lblTotal = new Label();
        lblTotal.Text = "Итого: 0.00 руб.";
        lblTotal.Location = new Point(20, 105);
        lblTotal.Size = new Size(300, 20);
        lblTotal.Font = new Font("Segoe UI", 10f, FontStyle.Bold);

        btnOrder = new Button();
        btnOrder.Text = "Оформить";
        btnOrder.Location = new Point(50, 140);
        btnOrder.Size = new Size(110, 32);
        btnOrder.Click += BtnOrder_Click;

        btnCancel = new Button();
        btnCancel.Text = "Отмена";
        btnCancel.Location = new Point(175, 140);
        btnCancel.Size = new Size(110, 32);
        btnCancel.Click += (s, e) => { this.DialogResult = DialogResult.Cancel; this.Close(); };

        lblError = new Label();
        lblError.Text = "";
        lblError.ForeColor = Color.Red;
        lblError.Location = new Point(20, 178);
        lblError.Size = new Size(310, 18);

        this.Controls.Add(lblProduct);
        this.Controls.Add(cmbProduct);
        this.Controls.Add(lblQuantity);
        this.Controls.Add(nudQuantity);
        this.Controls.Add(lblTotal);
        this.Controls.Add(btnOrder);
        this.Controls.Add(btnCancel);
        this.Controls.Add(lblError);

        LoadProducts();
    }

    private void LoadProducts()
    {
        _products = _api.GetProducts();
        cmbProduct.Items.Clear();
        foreach (var p in _products)
        {
            cmbProduct.Items.Add(new ProductItem(p));
        }
        if (cmbProduct.Items.Count > 0)
            cmbProduct.SelectedIndex = 0;
    }

    private void UpdateTotal()
    {
        if (cmbProduct.SelectedItem is ProductItem item)
        {
            decimal total = item.Product.Price * (decimal)nudQuantity.Value;
            lblTotal.Text = $"Итого: {total:F2} руб.";
        }
        else
        {
            lblTotal.Text = "Итого: 0.00 руб.";
        }
    }

    private void CmbProduct_SelectedIndexChanged(object? sender, EventArgs e) => UpdateTotal();
    private void NudQuantity_ValueChanged(object? sender, EventArgs e) => UpdateTotal();

    private void BtnOrder_Click(object? sender, EventArgs e)
    {
        lblError.Text = "";

        if (cmbProduct.SelectedItem is not ProductItem item)
        {
            lblError.Text = "Выберите товар";
            return;
        }

        int productId = item.Product.Id;
        int quantity = (int)nudQuantity.Value;

        var result = _api.CreateOrder(productId, quantity);
        if (result != null)
        {
            this.DialogResult = DialogResult.OK;
            this.Close();
        }
        else
        {
            lblError.Text = "Ошибка при создании заказа";
        }
    }

    private class ProductItem
    {
        public Product Product { get; }
        public ProductItem(Product p) { Product = p; }
        public override string ToString() => $"{Product.Name} — {Product.Price:F2} руб.";
    }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Forms\OrdersControl.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Forms\OrdersControl.cs",
@'
using S4_Client.Models;
using S4_Client.Services;

namespace S4_Client.Forms;

public class OrdersControl : UserControl
{
    private readonly ApiService _api = new ApiService();

    private Label lblTitle;
    private DataGridView dgvOrders;
    private Panel pnlButtons;
    private Button btnCreate;
    private Button btnDelete;
    private Button btnRefresh;

    public OrdersControl()
    {
        this.Dock = DockStyle.Fill;

        lblTitle = new Label();
        lblTitle.Text = "Заказы";
        lblTitle.Font = new Font("Segoe UI", 14f, FontStyle.Bold);
        lblTitle.Location = new Point(10, 10);
        lblTitle.Size = new Size(200, 30);

        dgvOrders = new DataGridView();
        dgvOrders.Location = new Point(10, 50);
        dgvOrders.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        dgvOrders.Size = new Size(this.Width - 20, this.Height - 110);
        dgvOrders.ReadOnly = true;
        dgvOrders.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvOrders.MultiSelect = false;
        dgvOrders.AllowUserToAddRows = false;
        dgvOrders.AllowUserToDeleteRows = false;
        dgvOrders.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;

        pnlButtons = new Panel();
        pnlButtons.Dock = DockStyle.Bottom;
        pnlButtons.Height = 50;
        pnlButtons.Padding = new Padding(5);

        btnCreate = new Button();
        btnCreate.Text = "Создать заказ";
        btnCreate.Location = new Point(10, 10);
        btnCreate.Size = new Size(130, 30);
        btnCreate.Click += BtnCreate_Click;

        btnDelete = new Button();
        btnDelete.Text = "Удалить";
        btnDelete.Location = new Point(150, 10);
        btnDelete.Size = new Size(110, 30);
        btnDelete.Click += BtnDelete_Click;

        btnRefresh = new Button();
        btnRefresh.Text = "Обновить";
        btnRefresh.Location = new Point(270, 10);
        btnRefresh.Size = new Size(110, 30);
        btnRefresh.Click += (s, e) => LoadData();

        pnlButtons.Controls.Add(btnCreate);
        pnlButtons.Controls.Add(btnDelete);
        pnlButtons.Controls.Add(btnRefresh);

        this.Controls.Add(lblTitle);
        this.Controls.Add(dgvOrders);
        this.Controls.Add(pnlButtons);

        LoadData();
    }

    public void LoadData()
    {
        var orders = _api.GetOrders();
        dgvOrders.Columns.Clear();
        dgvOrders.Rows.Clear();

        dgvOrders.Columns.Add("Id", "Id");
        dgvOrders.Columns.Add("ProductName", "Товар");
        dgvOrders.Columns.Add("Quantity", "Количество");
        dgvOrders.Columns.Add("TotalPrice", "Сумма");
        dgvOrders.Columns.Add("Status", "Статус");

        dgvOrders.Columns["Id"].Visible = false;

        foreach (var o in orders)
        {
            dgvOrders.Rows.Add(o.Id, o.ProductName, o.Quantity, o.TotalPrice.ToString("F2"), o.Status);
        }
    }

    private int GetSelectedOrderId()
    {
        if (dgvOrders.SelectedRows.Count == 0) return -1;
        return Convert.ToInt32(dgvOrders.SelectedRows[0].Cells["Id"].Value);
    }

    private void BtnCreate_Click(object? sender, EventArgs e)
    {
        var dialog = new OrderDialog(_api);
        if (dialog.ShowDialog() == DialogResult.OK)
        {
            LoadData();
        }
    }

    private void BtnDelete_Click(object? sender, EventArgs e)
    {
        int id = GetSelectedOrderId();
        if (id == -1)
        {
            MessageBox.Show("Выберите заказ для удаления", "Предупреждение", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return;
        }

        var confirm = MessageBox.Show("Удалить выбранный заказ?", "Подтверждение",
            MessageBoxButtons.YesNo, MessageBoxIcon.Question);
        if (confirm == DialogResult.Yes)
        {
            _api.DeleteOrder(id);
            LoadData();
        }
    }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Forms\ProductDialog.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Forms\ProductDialog.cs",
@'
using S4_Client.Models;

namespace S4_Client.Forms;

public class ProductDialog : Form
{
    public Product? Result { get; private set; }

    private Label lblName;
    private TextBox txtName;
    private Label lblDescription;
    private TextBox txtDescription;
    private Label lblPrice;
    private TextBox txtPrice;
    private Label lblStock;
    private TextBox txtStock;
    private Button btnSave;
    private Button btnCancel;
    private Label lblError;

    public ProductDialog(Product? product)
    {
        this.Text = product == null ? "Добавить товар" : "Редактировать товар";
        this.Size = new Size(380, 300);
        this.StartPosition = FormStartPosition.CenterParent;
        this.FormBorderStyle = FormBorderStyle.FixedDialog;
        this.MaximizeBox = false;
        this.MinimizeBox = false;

        lblName = new Label();
        lblName.Text = "Название:";
        lblName.Location = new Point(20, 20);
        lblName.Size = new Size(100, 20);

        txtName = new TextBox();
        txtName.Location = new Point(130, 18);
        txtName.Size = new Size(220, 25);
        txtName.Text = product?.Name ?? "";

        lblDescription = new Label();
        lblDescription.Text = "Описание:";
        lblDescription.Location = new Point(20, 55);
        lblDescription.Size = new Size(100, 20);

        txtDescription = new TextBox();
        txtDescription.Location = new Point(130, 53);
        txtDescription.Size = new Size(220, 25);
        txtDescription.Text = product?.Description ?? "";

        lblPrice = new Label();
        lblPrice.Text = "Цена:";
        lblPrice.Location = new Point(20, 90);
        lblPrice.Size = new Size(100, 20);

        txtPrice = new TextBox();
        txtPrice.Location = new Point(130, 88);
        txtPrice.Size = new Size(220, 25);
        txtPrice.Text = product?.Price.ToString("F2") ?? "";

        lblStock = new Label();
        lblStock.Text = "Остаток:";
        lblStock.Location = new Point(20, 125);
        lblStock.Size = new Size(100, 20);

        txtStock = new TextBox();
        txtStock.Location = new Point(130, 123);
        txtStock.Size = new Size(220, 25);
        txtStock.Text = product?.Stock.ToString() ?? "";

        btnSave = new Button();
        btnSave.Text = "Сохранить";
        btnSave.Location = new Point(60, 175);
        btnSave.Size = new Size(110, 32);
        btnSave.Click += BtnSave_Click;

        btnCancel = new Button();
        btnCancel.Text = "Отмена";
        btnCancel.Location = new Point(185, 175);
        btnCancel.Size = new Size(110, 32);
        btnCancel.Click += (s, e) => { this.DialogResult = DialogResult.Cancel; this.Close(); };

        lblError = new Label();
        lblError.Text = "";
        lblError.ForeColor = Color.Red;
        lblError.Location = new Point(20, 215);
        lblError.Size = new Size(330, 20);

        this.Controls.Add(lblName);
        this.Controls.Add(txtName);
        this.Controls.Add(lblDescription);
        this.Controls.Add(txtDescription);
        this.Controls.Add(lblPrice);
        this.Controls.Add(txtPrice);
        this.Controls.Add(lblStock);
        this.Controls.Add(txtStock);
        this.Controls.Add(btnSave);
        this.Controls.Add(btnCancel);
        this.Controls.Add(lblError);
    }

    private void BtnSave_Click(object? sender, EventArgs e)
    {
        lblError.Text = "";

        if (string.IsNullOrWhiteSpace(txtName.Text))
        {
            lblError.Text = "Введите название товара";
            return;
        }

        if (!decimal.TryParse(txtPrice.Text.Replace(',', '.'),
            System.Globalization.NumberStyles.Any,
            System.Globalization.CultureInfo.InvariantCulture,
            out decimal price) || price < 0)
        {
            lblError.Text = "Некорректная цена";
            return;
        }

        if (!int.TryParse(txtStock.Text, out int stock) || stock < 0)
        {
            lblError.Text = "Некорректный остаток";
            return;
        }

        Result = new Product
        {
            Name = txtName.Text.Trim(),
            Description = txtDescription.Text.Trim(),
            Price = price,
            Stock = stock
        };

        this.DialogResult = DialogResult.OK;
        this.Close();
    }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Forms\ProductsControl.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Forms\ProductsControl.cs",
@'
using S4_Client.Models;
using S4_Client.Services;

namespace S4_Client.Forms;

public class ProductsControl : UserControl
{
    private readonly ApiService _api = new ApiService();

    private Label lblTitle;
    private DataGridView dgvProducts;
    private Panel pnlButtons;
    private Button btnAdd;
    private Button btnEdit;
    private Button btnDelete;
    private Button btnRefresh;

    public ProductsControl()
    {
        this.Dock = DockStyle.Fill;

        lblTitle = new Label();
        lblTitle.Text = "Товары";
        lblTitle.Font = new Font("Segoe UI", 14f, FontStyle.Bold);
        lblTitle.Location = new Point(10, 10);
        lblTitle.Size = new Size(200, 30);

        dgvProducts = new DataGridView();
        dgvProducts.Location = new Point(10, 50);
        dgvProducts.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        dgvProducts.Size = new Size(this.Width - 20, this.Height - 110);
        dgvProducts.ReadOnly = true;
        dgvProducts.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvProducts.MultiSelect = false;
        dgvProducts.AllowUserToAddRows = false;
        dgvProducts.AllowUserToDeleteRows = false;
        dgvProducts.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvProducts.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;

        pnlButtons = new Panel();
        pnlButtons.Dock = DockStyle.Bottom;
        pnlButtons.Height = 50;
        pnlButtons.Padding = new Padding(5);

        btnAdd = new Button();
        btnAdd.Text = "Добавить";
        btnAdd.Location = new Point(10, 10);
        btnAdd.Size = new Size(110, 30);
        btnAdd.Click += BtnAdd_Click;

        btnEdit = new Button();
        btnEdit.Text = "Редактировать";
        btnEdit.Location = new Point(130, 10);
        btnEdit.Size = new Size(130, 30);
        btnEdit.Click += BtnEdit_Click;

        btnDelete = new Button();
        btnDelete.Text = "Удалить";
        btnDelete.Location = new Point(270, 10);
        btnDelete.Size = new Size(110, 30);
        btnDelete.Click += BtnDelete_Click;

        btnRefresh = new Button();
        btnRefresh.Text = "Обновить";
        btnRefresh.Location = new Point(390, 10);
        btnRefresh.Size = new Size(110, 30);
        btnRefresh.Click += (s, e) => LoadData();

        bool isAdmin = AppState.Role == "ADMIN";
        btnAdd.Visible = isAdmin;
        btnEdit.Visible = isAdmin;
        btnDelete.Visible = isAdmin;

        pnlButtons.Controls.Add(btnAdd);
        pnlButtons.Controls.Add(btnEdit);
        pnlButtons.Controls.Add(btnDelete);
        pnlButtons.Controls.Add(btnRefresh);

        this.Controls.Add(lblTitle);
        this.Controls.Add(dgvProducts);
        this.Controls.Add(pnlButtons);

        LoadData();
    }

    public void LoadData()
    {
        var products = _api.GetProducts();
        dgvProducts.Columns.Clear();
        dgvProducts.Rows.Clear();

        dgvProducts.Columns.Add("Id", "Id");
        dgvProducts.Columns.Add("Name", "Название");
        dgvProducts.Columns.Add("Description", "Описание");
        dgvProducts.Columns.Add("Price", "Цена");
        dgvProducts.Columns.Add("Stock", "Остаток");

        dgvProducts.Columns["Id"].Visible = false;

        foreach (var p in products)
        {
            dgvProducts.Rows.Add(p.Id, p.Name, p.Description, p.Price.ToString("F2"), p.Stock);
        }
    }

    private Product? GetSelectedProduct()
    {
        if (dgvProducts.SelectedRows.Count == 0) return null;
        var row = dgvProducts.SelectedRows[0];
        return new Product
        {
            Id = Convert.ToInt32(row.Cells["Id"].Value),
            Name = row.Cells["Name"].Value?.ToString() ?? "",
            Description = row.Cells["Description"].Value?.ToString() ?? "",
            Price = decimal.TryParse(row.Cells["Price"].Value?.ToString(), out var price) ? price : 0,
            Stock = Convert.ToInt32(row.Cells["Stock"].Value)
        };
    }

    private void BtnAdd_Click(object? sender, EventArgs e)
    {
        var dialog = new ProductDialog(null);
        if (dialog.ShowDialog() == DialogResult.OK && dialog.Result != null)
        {
            _api.CreateProduct(dialog.Result);
            LoadData();
        }
    }

    private void BtnEdit_Click(object? sender, EventArgs e)
    {
        var product = GetSelectedProduct();
        if (product == null)
        {
            MessageBox.Show("Выберите товар для редактирования", "Предупреждение", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return;
        }

        var dialog = new ProductDialog(product);
        if (dialog.ShowDialog() == DialogResult.OK && dialog.Result != null)
        {
            dialog.Result.Id = product.Id;
            _api.UpdateProduct(dialog.Result);
            LoadData();
        }
    }

    private void BtnDelete_Click(object? sender, EventArgs e)
    {
        var product = GetSelectedProduct();
        if (product == null)
        {
            MessageBox.Show("Выберите товар для удаления", "Предупреждение", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return;
        }

        var confirm = MessageBox.Show($"Удалить товар \"{product.Name}\"?", "Подтверждение",
            MessageBoxButtons.YesNo, MessageBoxIcon.Question);
        if (confirm == DialogResult.Yes)
        {
            _api.DeleteProduct(product.Id);
            LoadData();
        }
    }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Forms\RegisterForm.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Forms\RegisterForm.cs",
@'
using S4_Client.Services;

namespace S4_Client.Forms;

public class RegisterForm : Form
{
    private readonly ApiService _api = new ApiService();

    private Label lblTitle;
    private Label lblUsername;
    private TextBox txtUsername;
    private Label lblEmail;
    private TextBox txtEmail;
    private Label lblPassword;
    private TextBox txtPassword;
    private Label lblConfirm;
    private TextBox txtConfirm;
    private Button btnRegister;
    private Button btnBack;
    private Label lblError;

    public RegisterForm()
    {
        this.Text = "Регистрация";
        this.Size = new Size(400, 320);
        this.StartPosition = FormStartPosition.CenterScreen;
        this.FormBorderStyle = FormBorderStyle.FixedDialog;
        this.MaximizeBox = false;

        lblTitle = new Label();
        lblTitle.Text = "Регистрация";
        lblTitle.Font = new Font("Segoe UI", 14f, FontStyle.Bold);
        lblTitle.TextAlign = ContentAlignment.MiddleCenter;
        lblTitle.Location = new Point(0, 10);
        lblTitle.Size = new Size(384, 30);

        lblUsername = new Label();
        lblUsername.Text = "Имя пользователя:";
        lblUsername.Location = new Point(40, 52);
        lblUsername.Size = new Size(150, 18);

        txtUsername = new TextBox();
        txtUsername.Location = new Point(40, 72);
        txtUsername.Size = new Size(300, 25);

        lblEmail = new Label();
        lblEmail.Text = "Email:";
        lblEmail.Location = new Point(40, 105);
        lblEmail.Size = new Size(150, 18);

        txtEmail = new TextBox();
        txtEmail.Location = new Point(40, 125);
        txtEmail.Size = new Size(300, 25);

        lblPassword = new Label();
        lblPassword.Text = "Пароль:";
        lblPassword.Location = new Point(40, 158);
        lblPassword.Size = new Size(150, 18);

        txtPassword = new TextBox();
        txtPassword.Location = new Point(40, 178);
        txtPassword.Size = new Size(300, 25);
        txtPassword.PasswordChar = '*';

        lblConfirm = new Label();
        lblConfirm.Text = "Подтвердите пароль:";
        lblConfirm.Location = new Point(40, 211);
        lblConfirm.Size = new Size(150, 18);

        txtConfirm = new TextBox();
        txtConfirm.Location = new Point(40, 231);
        txtConfirm.Size = new Size(300, 25);
        txtConfirm.PasswordChar = '*';

        btnRegister = new Button();
        btnRegister.Text = "Зарегистрироваться";
        btnRegister.Location = new Point(40, 265);
        btnRegister.Size = new Size(160, 32);
        btnRegister.Click += BtnRegister_Click;

        btnBack = new Button();
        btnBack.Text = "Назад";
        btnBack.Location = new Point(215, 265);
        btnBack.Size = new Size(120, 32);
        btnBack.Click += (s, e) => this.Close();

        lblError = new Label();
        lblError.Text = "";
        lblError.ForeColor = Color.Red;
        lblError.Location = new Point(40, 302);
        lblError.Size = new Size(300, 18);

        this.Controls.Add(lblTitle);
        this.Controls.Add(lblUsername);
        this.Controls.Add(txtUsername);
        this.Controls.Add(lblEmail);
        this.Controls.Add(txtEmail);
        this.Controls.Add(lblPassword);
        this.Controls.Add(txtPassword);
        this.Controls.Add(lblConfirm);
        this.Controls.Add(txtConfirm);
        this.Controls.Add(btnRegister);
        this.Controls.Add(btnBack);
        this.Controls.Add(lblError);
    }

    private void BtnRegister_Click(object? sender, EventArgs e)
    {
        lblError.Text = "";

        if (string.IsNullOrWhiteSpace(txtUsername.Text) ||
            string.IsNullOrWhiteSpace(txtEmail.Text) ||
            string.IsNullOrWhiteSpace(txtPassword.Text) ||
            string.IsNullOrWhiteSpace(txtConfirm.Text))
        {
            lblError.Text = "Заполните все поля";
            return;
        }

        if (txtPassword.Text != txtConfirm.Text)
        {
            lblError.Text = "Пароли не совпадают";
            return;
        }

        var result = _api.Register(txtUsername.Text.Trim(), txtEmail.Text.Trim(), txtPassword.Text);
        if (result != null && !string.IsNullOrEmpty(result.Token))
        {
            MessageBox.Show("Регистрация успешна!", "Успех", MessageBoxButtons.OK, MessageBoxIcon.Information);
            this.Close();
        }
        else
        {
            lblError.Text = "Ошибка регистрации. Попробуйте другое имя или email.";
        }
    }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Models\Order.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Models\Order.cs",
@'
namespace S4_Client.Models;
public class Order
{
    public int Id { get; set; }
    public int ProductId { get; set; }
    public string ProductName { get; set; } = "";
    public int Quantity { get; set; }
    public decimal TotalPrice { get; set; }
    public string Status { get; set; } = "";
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Models\Product.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Models\Product.cs",
@'
namespace S4_Client.Models;
public class Product
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public string Description { get; set; } = "";
    public decimal Price { get; set; }
    public int Stock { get; set; }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Models\TokenResponse.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Models\TokenResponse.cs",
@'
namespace S4_Client.Models;
public class TokenResponse
{
    public string Token { get; set; } = "";
    public string Username { get; set; } = "";
    public string Role { get; set; } = "";
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Models\User.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Models\User.cs",
@'
namespace S4_Client.Models;
public class User
{
    public int Id { get; set; }
    public string Username { get; set; } = "";
    public string Email { get; set; } = "";
    public string Role { get; set; } = "";
}

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Program.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Program.cs",
@'
using S4_Client.Forms;
Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(false);
Application.Run(new LoginForm());

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\S4_Client.csproj
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\S4_Client.csproj",
@'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>S4_Client</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>

'@
    , [System.Text.UTF8Encoding]::new($false))

# S4_Client\Services\ApiService.cs
[System.IO.File]::WriteAllText(
    "$Base\S4_Client\Services\ApiService.cs",
@'
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json;
using S4_Client.Models;

namespace S4_Client.Services;

public class ApiService
{
    private readonly HttpClient _httpClient = new HttpClient();
    private const string BaseUrl = "http://localhost:8080";

    private void AddAuthHeader()
    {
        _httpClient.DefaultRequestHeaders.Authorization = null;
        if (!string.IsNullOrEmpty(AppState.Token))
        {
            _httpClient.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", AppState.Token);
        }
    }

    private T? PostJson<T>(string path, object body) where T : class
    {
        try
        {
            var json = JsonConvert.SerializeObject(body);
            var request = new HttpRequestMessage(HttpMethod.Post, BaseUrl + path);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            AddAuthHeader();
            var response = _httpClient.Send(request);
            var content = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            if (!response.IsSuccessStatusCode) return null;
            return JsonConvert.DeserializeObject<T>(content);
        }
        catch
        {
            return null;
        }
    }

    private T? GetJson<T>(string path) where T : class
    {
        try
        {
            var request = new HttpRequestMessage(HttpMethod.Get, BaseUrl + path);
            AddAuthHeader();
            var response = _httpClient.Send(request);
            var content = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            if (!response.IsSuccessStatusCode) return null;
            return JsonConvert.DeserializeObject<T>(content);
        }
        catch
        {
            return null;
        }
    }

    private T? PutJson<T>(string path, object body) where T : class
    {
        try
        {
            var json = JsonConvert.SerializeObject(body);
            var request = new HttpRequestMessage(HttpMethod.Put, BaseUrl + path);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            AddAuthHeader();
            var response = _httpClient.Send(request);
            var content = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            if (!response.IsSuccessStatusCode) return null;
            return JsonConvert.DeserializeObject<T>(content);
        }
        catch
        {
            return null;
        }
    }

    private bool DeleteRequest(string path)
    {
        try
        {
            var request = new HttpRequestMessage(HttpMethod.Delete, BaseUrl + path);
            AddAuthHeader();
            var response = _httpClient.Send(request);
            return response.IsSuccessStatusCode;
        }
        catch
        {
            return false;
        }
    }

    public TokenResponse? Login(string username, string password)
    {
        return PostJson<TokenResponse>("/api/auth/login", new { username, password });
    }

    public TokenResponse? Register(string username, string email, string password)
    {
        return PostJson<TokenResponse>("/api/auth/register", new { username, email, password });
    }

    public List<Product> GetProducts()
    {
        return GetJson<List<Product>>("/api/products") ?? new List<Product>();
    }

    public Product? CreateProduct(Product p)
    {
        return PostJson<Product>("/api/products", new { p.Name, p.Description, p.Price, p.Stock });
    }

    public Product? UpdateProduct(Product p)
    {
        return PutJson<Product>($"/api/products/{p.Id}", new { p.Name, p.Description, p.Price, p.Stock });
    }

    public bool DeleteProduct(int id)
    {
        return DeleteRequest($"/api/products/{id}");
    }

    public List<Order> GetOrders()
    {
        return GetJson<List<Order>>("/api/orders") ?? new List<Order>();
    }

    public Order? CreateOrder(int productId, int quantity)
    {
        return PostJson<Order>("/api/orders", new { productId, quantity });
    }

    public bool DeleteOrder(int id)
    {
        return DeleteRequest($"/api/orders/{id}");
    }
}

'@
    , [System.Text.UTF8Encoding]::new($false))

Write-Host ""
Write-Host "[S4_plan] Done! Created in: $Base"
Write-Host ""
Write-Host "  Build Java (offline):"
Write-Host "    mvn package -o -Dmaven.repo.local=..\libs\maven -DskipTests"
Write-Host ""
Write-Host "  Build C# (offline):"
Write-Host "    dotnet restore --packages ..\libs\nuget"
Write-Host "    dotnet build --no-restore"
Write-Host ""
