# generate_create_script.ps1
# Reads a folder and generates a PowerShell script that recreates it.
#
# Usage: .\generate_create_script.ps1 <FolderName>
# Example: .\generate_create_script.ps1 S3_plan
#
# Output: create_<FolderName>.ps1

param(
    [Parameter(Mandatory=$true)]
    [string]$FolderName
)

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$SourceDir  = Join-Path $ScriptDir $FolderName
$OutputFile = Join-Path $ScriptDir "create_${FolderName}_files.ps1"
$NoBOM      = [System.Text.UTF8Encoding]::new($false)

if (-not (Test-Path $SourceDir)) {
    Write-Host "[ERROR] Folder not found: $SourceDir"
    exit 1
}

Write-Host "[INFO] Reading: $SourceDir"

$lines = [System.Collections.Generic.List[string]]::new()

# Header
$lines.Add("# create_${FolderName}_files.ps1")
$lines.Add("# Auto-generated by generate_create_script.ps1")
$lines.Add("# Creates all files and folders for $FolderName")
$lines.Add("# Usage: .\create_${FolderName}_files.ps1")
$lines.Add("")
$lines.Add('$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path')
$lines.Add('$Base      = "$ScriptDir\' + $FolderName + '"')
$lines.Add("")

# Collect all directories
$allDirs = Get-ChildItem -Path $SourceDir -Recurse -Directory |
           Sort-Object FullName

$lines.Add("Write-Host `"[${FolderName}] Creating folders...`"")
$lines.Add('@(')
foreach ($dir in $allDirs) {
    $rel = $dir.FullName.Substring($SourceDir.Length).TrimStart('\','/')
    $lines.Add('    "$Base\' + $rel + '",')
}
$lines.Add(') | ForEach-Object { New-Item -ItemType Directory -Force -Path $_ | Out-Null }')
$lines.Add("")

# Collect all files
$allFiles = Get-ChildItem -Path $SourceDir -Recurse -File |
            Sort-Object FullName

$lines.Add("Write-Host `"[${FolderName}] Writing files...`"")
$lines.Add("")

foreach ($file in $allFiles) {
    $rel     = $file.FullName.Substring($SourceDir.Length).TrimStart('\','/')
    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.UTF8Encoding]::new($false))

    # Remove UTF-8 BOM if present
    if ($content.Length -gt 0 -and [int][char]$content[0] -eq 65279) {
        $content = $content.Substring(1)
    }

    # Escape the closing here-string marker inside content
    $escaped = $content -replace "'@", "'`@"

    $lines.Add("# $rel")
    $lines.Add('[System.IO.File]::WriteAllText(')
    $lines.Add('    "$Base\' + $rel + '",')
    $lines.Add("@'" )
    $lines.Add($escaped)
    $lines.Add("'@")
    $lines.Add('    , [System.Text.UTF8Encoding]::new($false))')
    $lines.Add("")
}

# Footer
$lines.Add("Write-Host `"`"")
$lines.Add("Write-Host `"[${FolderName}] Done! Created in: `$Base`"")
$lines.Add("Write-Host `"`"")
$lines.Add("Write-Host `"  Build Java (offline):`"")
$lines.Add("Write-Host `"    mvn package -o -Dmaven.repo.local=..\libs\maven -DskipTests`"")
$lines.Add("Write-Host `"`"")
$lines.Add("Write-Host `"  Build C# (offline):`"")
$lines.Add("Write-Host `"    dotnet restore --packages ..\libs\nuget`"")
$lines.Add("Write-Host `"    dotnet build --no-restore`"")
$lines.Add("Write-Host `"`"")

[System.IO.File]::WriteAllLines($OutputFile, $lines, $NoBOM)

Write-Host "[INFO] Generated: $OutputFile"
Write-Host "[INFO] Files included: $($allFiles.Count)"
Write-Host "[INFO] Folders included: $($allDirs.Count)"
